# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tk7ShBYOL6YtaIB3W8L-kfqQHuBf3Ew1
"""

!pip install pycryptodome

from Crypto.Cipher import DES
from Crypto.Util.Padding import pad, unpad

# Key must be 8 bytes long
key = b'12345678'

# Greek text to encrypt
greek_text = "Γειά σου Κόσμε"  # "Hello World" in Greek

# Encode the Greek text using ISO 8859-7
encoded_text = greek_text.encode('iso-8859-7')

# Initialize DES cipher in ECB mode
cipher = DES.new(key, DES.MODE_ECB)

# Encrypt the padded text
ciphertext = cipher.encrypt(pad(encoded_text, DES.block_size))
print("Encrypted (hex):", ciphertext.hex())

# Decrypt the ciphertext
decrypted_text = unpad(cipher.decrypt(ciphertext), DES.block_size)

# Decode back to Greek
decoded_text = decrypted_text.decode('iso-8859-7')
print("Decrypted text:", decoded_text)

######################################################3
Encrypted (hex): b2efe7fe4cd1c07c83b0b9f7f952d6ec
Decrypted text: Γειά σου Κόσμε

